[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.gd',
  'php82Extensions.zip',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Packages.composer'
]

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs'
]

[phases.build]
cmds = [
  'php artisan config:clear || true',
  'php artisan cache:clear || true'
]

[start]
cmd = 'bash railway-start.sh'
