[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.gd',
  'php82Extensions.zip',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.xml',
  'php82Extensions.curl',
  'php82Packages.composer'
]

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs --no-scripts'
]

[phases.build]
cmds = []

[start]
cmd = 'bash railway-start.sh'
